# -*- coding: utf-8 -*-
"""KnowledgeGraph.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16FLyT_QQtDcieYhjUps6fjXaDizatNAN
"""

import streamlit as st
import pandas as pd
import networkx as nx
import matplotlib.pyplot as plt

def create_knowledge_graph(df):
    G = nx.Graph()

    for index, row in df.iterrows():
        # Assuming the CSV has columns 'Source', 'Target', 'Relation'
        G.add_node(row['Source'])
        G.add_node(row['Target'])
        G.add_edge(row['Source'], row['Target'], relation=row['Relation'])

    return G

def draw_knowledge_graph(G):
    pos = nx.spring_layout(G)
    edge_labels = nx.get_edge_attributes(G, 'relation')

    nx.draw(G, pos, with_labels=True, node_size=700, node_color='skyblue', font_size=8, font_color='black', font_weight='bold')
    nx.draw_networkx_edge_labels(G, pos, edge_labels=edge_labels)

    st.pyplot()

def main():
    st.title("Knowledge Graph App")

    uploaded_file = st.file_uploader("Upload CSV file", type=["csv"])

    if uploaded_file is not None:
        df = pd.read_csv(uploaded_file)
        st.subheader("Data Preview:")
        st.write(df.head())

        knowledge_graph = create_knowledge_graph(df)

        st.subheader("Knowledge Graph Visualization:")
        draw_knowledge_graph(knowledge_graph)

if __name__ == "__main__":
    main()
